course_web/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import (
    include,
    path,
)

urlpatterns = [
    path("courses/", include("courses.urls")),
    path("admin/", admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

courses/urls.py
from django.urls import path

from . import views

app_name = "courses"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("login/", views.LoginView.as_view(), name="login"),
    path("logout/", views.Logout_View, name="logout"),
    path("course/<int:pk>/", views.CourseView.as_view(), name="course"),
    path("category/<int:pk>/", views.CategoryView.as_view(), name="categ"),
]

courses/models.py
from django.conf import settings
from django.core.validators import (
    MaxValueValidator,
    MinValueValidator,
)
from django.db import models

# Create your models here.


class CategoryModel(models.Model):
    name = models.CharField(max_length=50)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, null=True)
    # description = models.CharField(max_length=500)
    date_created = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["id"]

    def __str__(self):
        return self.name


class CourseModel(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=500)
    # text = models.
    rating = models.FloatField(default=0, validators=[MaxValueValidator(5), MinValueValidator(0)])
    category = models.ForeignKey("CategoryModel", on_delete=models.CASCADE)
    times_viewed = models.IntegerField(default=0)
    times_completed = models.IntegerField(default=0)
    date_created = models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["id"]

    def __str__(self):
        return self.name


class CourseCommentsModel(models.Model):
    posted_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    course = models.ForeignKey("CourseModel", on_delete=models.CASCADE)
    date_posted = models.DateTimeField(auto_now_add=True)
    date_edited = models.DateTimeField(auto_now=True)

courses/forms.py
from django import forms
from django.contrib.auth.forms import (
    AuthenticationForm,
    PasswordChangeForm,
    UserCreationForm,
)
from django.contrib.auth.models import User
from django.forms import ModelForm


class UserRegisterForm(UserCreationForm):
    username = forms.CharField(label="Username", widget=forms.TextInput(attrs={"class": "form-control"}))
    email = forms.EmailField(label="Email", widget=forms.EmailInput(attrs={"class": "form-control"}))
    password1 = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={"class": "form-control"}))
    password2 = forms.CharField(label="Repeat Password", widget=forms.PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(label="Username", widget=forms.TextInput(attrs={"class": "form-control"}))
    password = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={"class": "form-control"}))


class UserUpdateForm(ModelForm):
    username = forms.CharField(label="Username", widget=forms.TextInput(attrs={"class": "form-control"}))
    email = forms.EmailField(label="Email", widget=forms.EmailInput(attrs={"class": "form-control"}))
    first_name = forms.CharField(
        required=False, label="First Name", widget=forms.TextInput(attrs={"class": "form-control"})
    )
    last_name = forms.CharField(
        required=False, label="Last Name", widget=forms.TextInput(attrs={"class": "form-control"})
    )

    class Meta:
        model = User
        fields = ["username", "email", "first_name", "last_name"]


class ChangePassForm(PasswordChangeForm):
    old_password = forms.CharField(label="Old Password", widget=forms.PasswordInput(attrs={"class": "form-control"}))
    new_password1 = forms.CharField(label="New Password", widget=forms.PasswordInput(attrs={"class": "form-control"}))
    new_password2 = forms.CharField(
        label="Repeat New Password", widget=forms.PasswordInput(attrs={"class": "form-control"})
    )

    class Meta:
        model = User
        fields = ["old_password", "new_password1", "new_password2"]

courses/views.py
from django.contrib.auth import (
    login,
    logout,
)
from django.contrib.auth.views import LoginView
from django.shortcuts import (
    redirect,
    render,
)
from django.urls import reverse_lazy
from django.views import generic

from courses.forms import (
    UserLoginForm,
    UserRegisterForm,
)
from courses.models import (
    CategoryModel,
    CourseModel,
)

# Create your views here.


class IndexView(generic.View):
    template_name = "courses/index.html"

    def get(self, request):
        courses = CourseModel.objects.order_by("rating")
        categs = CategoryModel.objects.values()
        return render(request, self.template_name, {"courses": courses, "categs": categs})


class CourseView(generic.DetailView):
    template_name = "courses/course.html"
    model = CourseModel

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class CategoryView(generic.DeleteView):
    template_name = "courses/category.html"
    model = CategoryModel

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["courses"] = CourseModel.objects.filter(category__id=self.kwargs["pk"])
        return context


class LoginView(LoginView):
    form_class = UserLoginForm
    template_name = "courses/login.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        return dict(list(context.items()))

    def get_success_url(self):
        return reverse_lazy("courses:index")


class RegisterView(generic.CreateView):
    form_class = UserRegisterForm
    template_name = "courses/register.html"
    success_url = reverse_lazy("courses:login")

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect("courses:index")


def Logout_View(request):
    logout(request)
    return redirect("courses:index")

courses/templates/courses/base.html
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<!DOCTYPE html>

<style>
    nav.navbar a {color: #fff !important;}
</style>

<html>

<head>
    <meta charset="utf-8">
</head>

<body>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

    <nav class="navbar navbar-expand-lg bg-dark">
        <div class="container-fluid" style="margin-left: 180px; margin-right: 300px;">
            <a class="navbar-brand" href="{% url 'courses:index' %}">Home</a>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'courses:login' %}">Login_Tmp</a>
                    </li>
                </ul>
                <ul class="navbar-nav ms-auto">
                    {% if request.user.is_authenticated %}
                    <li class="nav-item text-primary">
                        <a href="{% url 'courses:logout' %}">{{ user.username }}</a> |
                        <a href="{% url 'courses:logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'courses:register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'courses:login' %}">Login</a>
                    </li>{% endif %}
                </ul>
            </div>
        </div>
    </nav>

    {% block content %}

    {% endblock content %}

</body>

</html>

courses/templates/courses/category.html
{% extends 'courses/base.html' %}
{% load static %}

{% block content %}
<html>

<head>
    <title>
        {{ object.name }}
    </title>
</head>

<body>
    <div class="container" style="max-width: 75%; text-align: center; margin:0 auto;">
        <h1>{{ object.name }}</h1>
        {% for course in courses %}
        <div class="card" , style="max-width: 50%; margin:1% auto;">
            <h3><a href="{% url 'courses:course' course.id %}" class="nav-link">{{ course.name }}</a></h3>
            <p>{{ course.description }}</p>
            <p class="mx-3" style="text-align: right"><img width="5%" src="{% static 'viewed_eye.jpg' %}"
                    alt="Viewed Eye">
                {{ course.times_viewed }}
                <img width="3%" src="{% static 'completed.png' %}" alt="Completed">
                {{ course.times_completed }}
            </p>
        </div>
        {% endfor %}
    </div>
</body>

</html>
{% endblock content %}

courses/templates/courses/course.html
{% extends 'courses/base.html' %}
{% load markdownify %}

{% block content %}
<html>

<head>
    <title>{{ object.name }}</title>
</head>

<body>
    <div class="container" style="max-width: 75%; text-align: center; margin:0 auto;">
        <h1>{{ object.name }}</h1>
        <h5>Short Description:</h5>
        <p>{{ object.description }}</p>
        {{'Some *test* [link](http://127.0.0.1:8000/courses/course/2/)'|markdownify }}
        {{'#bruh'|markdownify}}
        <hr>
    </div>
</body>

</html>
{% endblock content %}

courses/templates/courses/index.html
{% extends 'courses/base.html' %}
{% load static %}

{% block content %}

<html>

<head>
    <title>Courses website</title>
</head>

<body>

    <div class="d-flex flex-column flex-shrink-0 p-3 bg-light" style="width: 20%; position:absolute;">
        <span class="fs-4 mx-3">Categories</span>
        <hr>
        <ul class="nav nav-pills flex-column">
            <li class="nav-item">
                <a href="{% url 'courses:login' %}" class="nav-link">
                    Create New Note
                </a>
            </li>
            <hr>
            <div>
                {% for cat in categs %}
                <li class="nav-item">
                    <a href="{% url 'courses:login' %}" class="nav-link">
                        {{ cat.name }}
                    </a>
                </li>
                {% endfor %}
            </div>
        </ul>
        <hr>
    </div>


    <div class="container" style="max-width: 75%; text-align: center; margin:0 auto;">
        {% for course in courses %}
        <div class="card" , style="max-width: 50%; margin:1% auto;">
            <h3><a href="{% url 'courses:login' %}" class="nav-link">{{ course.name }}</a></h3>
            <p>{{ course.description }}</p>
            <p class="mx-3" style="text-align: right"><img width="5%" src="{% static 'viewed_eye.jpg' %}" alt="Viewed Eye">
                {{ course.times_viewed }}
                <img width="3%" src="{% static 'completed.png' %}" alt="Completed">
                {{ course.times_completed }}
            </p>
        </div>
        {% endfor %}
    </div>
</body>

</html>

{% endblock content %}

courses/templates/courses/login.html
{% extends 'courses/base.html' %}

{% block content %}

<html>

<head>
    <title>Login</title>
</head>

<body>
    <div class="container" style="max-width: 25%; text-align: center; margin:0 auto;">
        <h1>Login</h1>
        <div class="card">
            <form method="POST" class="m-3">
                {% csrf_token %}
                <div class="form-error">{{ form.non_field_errors }}</div>
                {% for f in form %}
                <p><label class="form-label" for="{ f.id_for_label }">{{f.label}}: </label>{{ f }}</p>
                <div class="form-error">{{ f.errors }}</div>
                {% endfor %}
                <button class="btn btn-primary" type="submit">Login</button>
            </form>
        </div>
</body>

</html>

{% endblock content %}

courses/templates/courses/register.html
{% extends 'courses/base.html' %}

{% block content %}

<html>

<head>
    <title>Register</title>
</head>

<body>
    <div class="container" style="max-width: 30%; text-align: center; margin:0 auto;">
        <h1>Register New Account</h1>
        <div class="card">
            <form method="POST" class="m-3">
                {% csrf_token %}
                {% for f in form %}
                <p><label class="form-label">{{f.label}}: </label>{{ f }}</p>
                <div class="form-error">{{ f.errors }}</div>
                {% endfor %}
                <button class="btn btn-primary" type="submit">Register</button>
            </form>
        </div>
</body>

</html>

{% endblock content %}